### Cadastrar Administrativo
POST https://localhost:5001/api/administrativo/create
Content-Type: application/json

{
    "id" : 13,
    "responsavel": "Jhon",
    "matriculaAdm": "1"
}

### Listar Administrativo
GET https://localhost:5001/api/administrativo/list

### Buscar Administrativo pela matricula
GET https://localhost:5001/api/administrativo/getbyid/12

### Deletar Administrativo pela matricula
DELETE  https://localhost:5001/api/administrativo/delete/Jhon

###
PUT  https://localhost:5001/api/administrativo/update
Content-Type: application/json

{
    "id" : 13,
    "responsavel": "João",
    "matriculaAdm": "2"
}